### PR TITLE
Nlmixr2 nonmem

### PR DESCRIPTION
**Pull request by billdenney**
For reasons I don't understand, this PR is not showing up in the #11 PR.  These are on top of that.

The changes include updating Hugo to the current version (`blogdown::install_hugo()`).

### CODE REVIEW

**Comment by mattfidler** [comment]
You arent picking up Justin's changes.  I think that is why. Maybe you can merge the two

**Comment by billdenney** [comment]
I pulled the current branch, and that didn't seem to have any additional changes.  I'm not sure how to make it work.

**Comment by kestrel99** [comment]
Hi Bill,

I’ve gone over your pull request line by line and can’t find any differences with the published version. Can you check? In the meantime I’ve merged #11. If something’s missing, can you open a new pull request? I won’t announce the new post until I’ve heard from you.

Best
Justin

—
Justin Wilkins, PhD
—
Occams
Kirchnerstraße 22
59457 Werl
Germany
www.occams.com
+49 2922 927 8843
***@***.******@***.***>
linkedin.com/in/justinjwilkins<https://www.linkedin.com/in/justinjwilkins/>

***@***.***

**Comment by billdenney** [comment]
It was minor.  I don't know why it's not showing up.  No need to wait for this.

**Pull request closed without merging**
