### PR TITLE
rxode2 release

### PR DESCRIPTION
**Pull request by mattfidler**
@kestrel99 can you look at this

### CODE REVIEW

**Comment by kestrel99** [comment]
I’ve added some review comments! Let me know if OK. Do we not want to mention somewhere how to fix the CRAN issue when all the packages are not fully in sync? (ie download from r-universe)


—
Justin Wilkins, PhD
—
Upcoming absence:
28 October 2022 – 4 November 2022, inclusive
—
Occams
Kirchnerstraße 22
59457 Werl
Germany
www.occams.com
+49 2922 927 8843
***@***.******@***.***>
linkedin.com/in/justinjwilkins<https://www.linkedin.com/in/justinjwilkins/>

***@***.***

**Comment by mattfidler** [comment]
Since everything is now in sync I dont think we need to here.  It will
simply get lost.

**Comment by kestrel99** [comment]
OK. If you’re happy with the edits I’ll process the pull request


—
Justin Wilkins, PhD
—
Upcoming absence:
28 October 2022 – 4 November 2022, inclusive
—
Occams
Kirchnerstraße 22
59457 Werl
Germany
www.occams.com
+49 2922 927 8843
***@***.******@***.***>
linkedin.com/in/justinjwilkins<https://www.linkedin.com/in/justinjwilkins/>

***@***.***

**Comment by mattfidler** [comment]
Nevermind.  Add it back  I missed a single delaration

**Comment by mattfidler** [comment]
I am happy with it now.  I added `rxode2` 2.0.10, which I also just submitted to CRAN.  If you think anything should read differently, let me know.

**Review by kestrel99 — APPROVED** [review]

**Pull request merged**
