### PR TITLE
Babelmixr nonmem

### PR DESCRIPTION
**Pull request by mattfidler**

### CODE REVIEW

**Comment by mattfidler** [comment]
Done from my end. 

Maybe you can think of something to make it read better.

**Comment by kestrel99** [comment]
I've made some suggestions, let me know if you agree before I commit...

**Review by kestrel99 — COMMENTED** [review]
I've made some suggestions - let me know if you agree. If yes I'll merge

**Comment by mattfidler** [comment]
Looks good to me

**Comment by kestrel99** [comment]
Merged


—
Justin Wilkins, PhD
—
Occams
Kirchnerstraße 22
59457 Werl
Germany
www.occams.com
+49 2922 927 8843
***@***.******@***.***>
linkedin.com/in/justinjwilkins<https://www.linkedin.com/in/justinjwilkins/>

***@***.***

**Pull request merged**
